### ISSUE TITLE
rspec tests fail using this module

### ISSUE THREAD

**Issue by blackknight36** [Nextdoor/puppet_thycotic#18]
Running rspec unit tests when this module is installed fails due to a missing parseconfig dependency.  There is an error shown by rspec as listed below.

> Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/getsecret: cannot load such file -- parseconfig

The parseconfig gem *is* installed so I am not sure what is causing this error.
```
15:25 $ gem list parseconfig

*** LOCAL GEMS ***

parseconfig (1.0.8)
```

Any suggestions on how to fix this?

**Comment by diranged** [comment]
Hrmm. I don't have that issue on our end. How are you installing the module?

**Comment by blackknight36** [comment]
For rspec I added the module to the .fixtures.yml and ran rake spec_prep.  Rspec automatically installs modules from this file to the spec/fixtures/modules directory when running spec_prep or rake spec.  I did find that adding "require 'parseconfig'" to spec/spec_helper.rb makes the error go away but I'm still having an issue getting rspec to load the proper configuration file.

For example, I am getting an error like this.

```
Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a Function Call, Could not initialize Thycotic object: can't find user for puppet at /home/00/username/projects/puppet/modules/dart/spec/fixtures/modules/dart/manifests/mdct_00sv.pp:32:20 on node mdct-00sv.example.com
```

**Comment by blackknight36** [comment]
Any idea how to fix the error mentioned previously?  I'm still getting failures any time that I run rspec such as follows.

```
5) dart::mdct_00sv on centos-7-x86_64 should contain File[/tmp/password.txt] with show_diff => false
     Failure/Error: raise Puppet::ParseError, "Could not initialize Thycotic object: #{e}"
     
     Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a Function Call, Could not initialize Thycotic object: Could not load configuration. Please see README. Supplied config paths: . (file: projects/puppet/modules/dart/spec/fixtures/modules/dart/manifests/mdct_00sv.pp, line: 33, column: 22) on node mdct-00sv.example.com
```

The rspec example causing this failure is just a simple file resource as follows.

```
it do
        is_expected.to contain_file('/tmp/password.txt')
            .with({
              :show_diff => false,
            })
      end
```

**Comment by diranged** [comment]
Ah - it took a while to find this, sorry.. see https://github.com/Nextdoor/puppet_thycotic/blob/master/lib/puppet/parser/functions/getsecret.rb#L125-L134. The issue is likely that you haven't set the `unittest` variable flag, ensuring that during a unit test, the function is not actually executed. We set that in our `scenarios.yml` file for the rspec test runner..

**Comment by blackknight36** [comment]
@diranged Thanks, that appears to fix it.  I added a custom fact to our spec/spec_helper.rb file and the unit tests are passing now.  For example:

```
add_custom_fact :unittest, true
```

I can submit a PR to document this along with the gems needed to make rspec work.

**Comment by blackknight36** [comment]
Thanks for the help, I am going to close this issue.
