### ISSUE TITLE
Invalid multibyte escape

### ISSUE THREAD

**Issue by seanmckinley** [Nextdoor/puppet_thycotic#8]
When running puppet on a node and trying to pull a secret out of SS, the puppet run errors with the following:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/parser/functions/getsecret: invalid multibyte escape: /\A(?:[\x9\xa\xd\x20-\x7F]|(?:[\x8E\xA1-\xFE][\xA1-\xFE])|(?:\x8F[\xA1-\xFE][\xA1-\xFE]))*\z/
```

**Comment by seanmckinley** [comment]
Alright, figured this out. We're running ruby 1.9, and after inspecting the gemfile it turns out the soap4r-ruby19 gem rather than just soap4r. Turns out reading is important.

Thanks for the cool module guys.

**Comment by diranged** [comment]
:) Glad you like it ... feel free to contribute to the code or docs if anything was unclear!

**Comment by seanmckinley** [comment]
Will do.

I do have one other issue, if you don't mind me asking here; I'm noticing that when dealing with internally hosted secret server, since we're using our own certificate authority the SOAP calls made by the puppet master all return the following:

Could not create SOAP Driver from URL https://oursecretserver.pvt/webservices/SSWebService.asmx: certificate verify failed
2015-08-06 01:08:44,223 WARN  [puppet-server] Puppet (1/3) Trying again...
2015-08-06 01:08:44,360 WARN  [puppet-server] Puppet Could not create SOAP Driver from URL https://oursecretserver.pvt/webservices/SSWebService.asmx: certificate verify failed

After a bit of digging, it seems the soap4r-ruby1.9 gem doesn't make use of the operating system's certificate bundle (our puppet master is running on CentOS6.5). Is there any cheap, easy way you might know of for getting around this? I looked through quite a bit of the puppet_thycotic code, as well as the soap4r-ruby1.9 gem, but I didn't see much in the way of telling it to use a particular cert or certificate store. If you've a good idea where to start, I can go from there and get a pull request in.

Also if you'd rather I raise this issue on GitHub, I can totally do that too.

Thanks,

Sean

________________________________
